CREATE VIEW SET2.budget_di AS
SELECT
	B.ACC_0 AS Compte,
	G.DES_0,
	B.CCE1_0 AS Qui,
	B.CCE2_0 AS Ou,
	B.CCE3_0 AS Projet,
	C.DES_0 AS Libellé,
	B.AMT_0,
	B.AMT_1,
	B.AMT_2,
	B.AMT_3,
	B.AMT_4,
	B.AMT_5,
	B.AMT_6,
	B.AMT_7,
	B.AMT_8,
	B.AMT_9,
	B.AMT_10,
	B.AMT_11,
	B.AMT_12,
	B.BUD_0,
	B.AMTATT_0,
	B.AMTCMM_0,
	B.AMTREA_0,
	B.FIY_0,
	B.REVDAT_0,
	B.VER_0
FROM SET2.BUD AS B
INNER JOIN SET2.CACCE AS C
ON B.CCE3_0 = C.CCE_0
INNER JOIN SET2.GACCOUNT AS G
ON B.ACC_0 = G.ACC_0